import React from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const nav = [
  ['/', 'Inicio'], ['/funcionalidades', 'Funcionalidades'], ['/playas', 'Playas'], ['/alertas', 'Alertas'], ['/sobre-nosotros', 'Sobre nosotros']
];

function Icon({ children }) { return <div className="icon">{children}</div>; }
function Placeholder({ wide=false, tall=false }) { return <div className={`placeholder ${wide?'wide':''} ${tall?'tall':''}`}><span>▧</span></div>; }
function Button({children, light=false}) { return <a className={`btn ${light?'btn-light':'btn-primary'}`} href="/playas">{children}</a>; }
function TopNav(){
  return <header className="topbar">
    <a className="brand" href="/"><span className="brand-mark">▣</span><span>SurfTracker</span></a>
    <nav>{nav.map(([href,label])=><a key={href} href={href}>{label}</a>)}</nav>
    <div className="actions"><a href="/playas">Explorar</a><a className="login" href="/inicio">Ingresar</a></div>
  </header>
}
function Footer(){
  return <footer className="footer">
    <div><b>Logo</b><p>Información marítima confiable para planificar visitas seguras al mar.</p></div>
    <div><b>Explorar</b><a>Inicio</a><a>Playas</a><a>Alertas</a></div>
    <div><b>Soporte</b><a>Consultas</a><a>Ayuda</a><a>Contacto</a></div>
    <div><b>Social</b><a>Instagram</a><a>Facebook</a><a>LinkedIn</a></div>
  </footer>
}
function PhotoCard({title, text, type='ocean'}){ return <article className={`photo-card ${type}`}><div><h3>{title}</h3><p>{text}</p></div></article> }
function SmallCard({title, text, dark=false, icon='☼'}){ return <article className={`small-card ${dark?'dark-card':''}`}><Icon>{icon}</Icon><h3>{title}</h3><p>{text}</p></article> }
function Stat({num, label}){ return <div className="stat"><strong>{num}</strong><span>{label}</span></div> }
function Testimonial({name='Usuario', text='Información clara, rápida y útil para decidir cuándo visitar la playa.'}){ return <article className="quote"><div className="stars">★★★★★</div><p>{text}</p><b>{name}</b></article> }
function Accordion(){ return <div className="accordion">{['¿Qué es SurfTracker?','¿Cómo se actualizan los pronósticos?','¿Puedo activar alertas personalizadas?','¿Qué playas están disponibles?','¿Necesito una cuenta?'].map(q=><details key={q} open={q.includes('Qué')}><summary>{q}</summary><p>SurfTracker centraliza información del estado del mar, condiciones de seguridad, recomendaciones y alertas para una mejor experiencia de usuario.</p></details>)}</div> }
function CTA({title='Comienza tu viaje hoy', text='Planifica tus próximas visitas al mar con datos claros y alertas oportunas.'}){ return <section className="cta"><h2>{title}</h2><p>{text}</p><div><Button light>Comenzar</Button><Button light>Ver playas</Button></div><Placeholder wide tall/></section> }

function Inicio(){ return <main>
  <TopNav/>
  <section className="hero split light reveal"><div><h1>Planifica tu próxima visita al mar con información confiable</h1><p>Accede a datos actualizados sobre playas, clima marítimo, oleaje, seguridad y recomendaciones para tomar mejores decisiones antes de salir.</p><div className="row"><Button>Comenzar</Button><Button light>Ver más</Button></div></div><div className="hero-image surfer"></div></section>
  <section className="dark reveal"><div className="center"><h2>Información actual del mar</h2><p>Datos relevantes para conocer el estado de las playas antes de visitarlas.</p></div><div className="grid3"><PhotoCard title="Altura de olas" text="Conoce el comportamiento del oleaje."/><PhotoCard title="Velocidad del viento" text="Consulta las condiciones actuales." type="wind"/><PhotoCard title="Nivel de riesgo" text="Identifica playas más seguras." type="risk"/></div></section>
  <section className="light reveal"><div className="center"><h2>Lo que enfrentas hoy</h2><p>Riesgos frecuentes que puedes prevenir con información anticipada.</p></div><div className="grid3"><PhotoCard title="Predicciones poco precisas" text="Evita información dispersa." type="map"/><PhotoCard title="Tiempo no actualizado" text="Consulta datos recientes." type="clock"/><PhotoCard title="Condiciones peligrosas" text="Recibe alertas importantes." type="hands"/></div></section>
  <section className="blue reveal"><div className="center"><h2>Lo que obtienes con Surf Tracker</h2><p>Herramientas clave para una salida más informada.</p></div><div className="grid4"><SmallCard title="Pronóstico del mar" text="Oleaje, viento y clima." icon="☼"/><SmallCard title="Alertas de seguridad" text="Avisos importantes." icon="⚠"/><SmallCard title="Playas recomendadas" text="Según tus preferencias." icon="◉"/><SmallCard title="Información clara" text="Todo en un solo lugar." icon="ⓘ"/></div></section>
  <section className="dark split reveal"><div><h2>Tu panel de control para el mar</h2><p>Visualiza datos, alertas y recomendaciones desde una interfaz simple, clara y orientada al usuario.</p><Button>Explorar playas</Button></div><Placeholder wide tall/></section>
  <section className="light reveal"><div className="center"><h2>Quién se beneficia aquí</h2><p>Diseñado para personas que necesitan información confiable antes de ir al mar.</p></div><div className="grid3"><PhotoCard title="Familias" text="Visitas más seguras." type="family"/><PhotoCard title="Surfistas" text="Mejores condiciones."/><PhotoCard title="Turistas" text="Planificación sencilla." type="tour"/></div></section>
  <section className="dark reveal"><div className="center"><h2>Cómo funciona Surf Tracker</h2><p>Un flujo simple para planificar mejor.</p></div><div className="grid3"><PhotoCard title="Busca una playa" text="Encuentra información por ubicación."/><PhotoCard title="Revisa el pronóstico" text="Consulta condiciones actuales." type="wind"/><PhotoCard title="Planifica con seguridad" text="Toma mejores decisiones." type="map"/></div></section>
  <section className="light reveal"><div className="center"><Icon>▦</Icon><h2>Visualiza todo en un vistazo</h2><p>Una experiencia limpia para consultar datos esenciales rápidamente.</p></div><div className="image-large coast"></div></section>
  <CTA/>
  <Footer/>
</main> }

function Funcionalidades(){ return <main><TopNav/><section className="page-head"><h1>Funcionalidades de Surf Tracker</h1><p>Explora todo lo que puedes consultar para planificar tu visita.</p></section><section className="dark reveal"><div className="center"><h2>Lo que ofrece Surf Tracker</h2><p>Información clara para tomar decisiones con confianza.</p></div><div className="feature-layout"><div className="grid2">{['Pronósticos marítimos','Personalización por región','Alertas en tiempo real','Datos históricos'].map((t,i)=><SmallCard key={t} dark title={t} text="Información marítima útil y actualizada." icon={['☼','⌖','⚠','◷'][i]}/>)}</div><article className="dark-panel"><Placeholder tall/><h3>Indicadores de condiciones favorables o peligrosas</h3><p>Evalúa rápidamente el estado de cada playa.</p></article></div></section><section className="light split"><div><h2>Visualiza todo en un solo lugar</h2><p>SurfTracker reúne pronóstico, alertas, playas y recomendaciones en una interfaz pensada para usuarios reales.</p></div><Placeholder tall/></section><section className="dark"><div className="center"><h2>Por qué elegir Surf Tracker</h2></div><div className="grid4"><SmallCard dark title="Información actualizada" text="Datos recientes."/><SmallCard dark title="Personalización" text="Según necesidades."/><SmallCard dark title="Diseño sencillo" text="Uso rápido."/><SmallCard dark title="Alertas confiables" text="Avisos oportunos."/></div></section><section className="light"><h2>Preguntas</h2><Accordion/></section><CTA title="Comienza tu experiencia hoy"/><Footer/></main>}

function Playas(){ return <main><TopNav/><section className="page-head"><h1>Playas de Perú</h1><p>Explora playas, condiciones y recomendaciones.</p></section><section className="dark split"><div><h2>Encuentra tu playa ideal con filtros inteligentes</h2><p>Busca por región, nivel de riesgo, oleaje y condiciones actuales.</p><Button>Explorar</Button></div><div className="stack">{['Por región','Por condición','Por tipo','Por seguridad'].map(x=><SmallCard key={x} dark title={x} text="Filtra los resultados según tus preferencias."/>)}</div></section><section className="light"><h2>Explora</h2><div className="beach-grid">{['Punta Hermosa','La Herradura','Pimentel','Máncora','Huanchaco','Paracas'].map(x=><article className="beach"><Placeholder/><h3>{x}</h3><p>Perú · 24°C</p></article>)}</div></section><section className="dark center"><Icon>▥</Icon><h2>Visualiza todas las playas en el mapa de Perú</h2><p>Consulta ubicaciones y condiciones desde una vista clara.</p><Placeholder wide tall/></section><section className="light split"><div><h2>Las mejores playas para hoy según las condiciones actuales</h2><p>Recomendaciones generadas con base en el estado del mar.</p></div><div className="side-list">{['Óptima para nadar','Clima ideal','Cerca de mar','Punta Hermosa'].map(x=><article><Placeholder/><h3>{x}</h3><p>Condición favorable.</p></article>)}</div></section><section className="dark"><h2>Preguntas</h2><Accordion/></section><CTA title="Recibe alertas personalizadas"/><Footer/></main>}

function Playa(){ return <main><TopNav/><section className="product light"><div><h1>Digital product name</h1><div className="rating">★★★★★ Favorable</div><div className="filters"><SmallCard title="Condición actual" text="Buen estado."/><SmallCard title="Riesgo" text="Bajo."/><SmallCard title="Oleaje" text="Moderado."/></div><h3>Información detallada</h3><ul>{['Altura de olas aproximada','Viento y temperatura','Nivel de seguridad','Recomendaciones para visitantes','Servicios cercanos'].map(i=><li>{i}</li>)}</ul></div><aside><Placeholder tall/><Button>Guardar</Button></aside></section><section className="dark split"><Placeholder tall/><div><h2>Condiciones en tiempo real</h2><p>Información actualizada para esta playa.</p><div className="mini-stats"><Stat num="24°C" label="Temperatura"/><Stat num="1.2m" label="Oleaje"/></div></div></section><section className="light"><div className="center"><h2>Pronóstico horario</h2></div><div className="grid4"><SmallCard title="Mañana" text="Oleaje moderado"/><SmallCard title="Tarde" text="Viento ligero"/><SmallCard title="Noche" text="Baja visibilidad"/><SmallCard title="Riesgo" text="Medio"/></div></section><section className="blue"><h2>Alertas activas</h2><div className="grid4"><SmallCard title="Corrientes" text="Precaución"/><SmallCard title="Oleaje" text="Moderado"/><SmallCard title="Viento" text="Ligero"/><SmallCard title="Marea" text="Normal"/></div></section><section className="dark"><h2>Consultas</h2><Accordion/></section><section className="light"><h2>Lo que dicen</h2><div className="grid3"><Testimonial/><Testimonial/><Testimonial/></div></section><section className="dark split"><div><h2>Contacta con nosotros</h2><p>Email, teléfono y canales de atención disponibles.</p></div><Placeholder tall/></section><Footer/></main>}

function Alertas(){ return <main><TopNav/><section className="page-head"><h1>Alertas de seguridad</h1><p>Recibe avisos sobre condiciones peligrosas antes de visitar una playa.</p></section><section className="dark"><div className="center"><h2>Tipos de alertas disponibles</h2></div><div className="grid3"><SmallCard dark title="Condiciones peligrosas" text="Oleaje, viento o marea."/><SmallCard dark title="Cambios climáticos" text="Eventos detectados."/><SmallCard dark title="Recomendación de seguridad" text="Indicaciones personalizadas."/></div></section><section className="light"><div className="center"><h2>Lo que dicen</h2></div><div className="grid3"><Testimonial/><Testimonial/><Testimonial/></div></section><section className="dark split"><div><h2>Alertas personalizadas que funcionan</h2><p>Configura tus playas favoritas y recibe notificaciones útiles.</p><Button>Crear alerta</Button></div><Placeholder tall/></section><section className="light"><h2>Cómo activar tus alertas</h2><div className="grid3"><SmallCard title="Elige tu playa favorita" text="Selecciona ubicación."/><SmallCard title="Configura preferencias" text="Nivel de alerta."/><SmallCard title="Recibe notificaciones" text="Avisos oportunos."/></div></section><CTA title="Comienza a recibir alertas hoy"/><Footer/></main>}

function Sobre(){ return <main><TopNav/><section className="page-head"><h1>Conoce Surf Tracker</h1><p>Una propuesta para mejorar la planificación y seguridad en playas.</p></section><section className="dark center"><h2>Por qué existe Surf Tracker</h2><p>Surge para centralizar información dispersa sobre el mar, playas, clima y seguridad.</p><div className="image-large"></div></section><section className="light"><div className="center"><h2>Quiénes somos</h2></div><div className="team-grid">{['Luis Méndez','María Torres','Diego Silva','Ana Ruiz','Raúl Vega','Lucía Ortega'].map(x=><article><Placeholder/><h3>{x}</h3><p>Equipo SurfTracker</p></article>)}</div></section><section className="blue stats-wrap"><div><h2>Números que hablan de nuestro compromiso</h2><p>Indicadores del alcance del producto.</p></div><div className="stats-grid"><Stat num="45,000+" label="Usuarios informados"/><Stat num="28" label="Playas monitoreadas"/><Stat num="120,0" label="Datos analizados"/><Stat num="89%" label="Satisfacción"/></div></section><section className="dark social"><a>Twitter</a><a>Facebook</a><a>LinkedIn</a><a>Instagram</a></section><section className="light split"><div><h2>Ponte en contacto con nosotros</h2><p>Queremos ayudarte a planificar tus próximas visitas al mar.</p></div><Placeholder tall/></section><CTA title="Comienza tu aventura marina hoy"/><Footer/></main>}

function App(){
  const path = window.location.pathname;
  if(path.startsWith('/funcionalidades')) return <Funcionalidades/>;
  if(path.startsWith('/playas')) return <Playas/>;
  if(path.startsWith('/playa')) return <Playa/>;
  if(path.startsWith('/alertas')) return <Alertas/>;
  if(path.startsWith('/sobre-nosotros')) return <Sobre/>;
  return <Inicio/>;
}

createRoot(document.getElementById('root')).render(<App />);
